services:
  php:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html/
    networks:
      - base_production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.laravel.rule=HostRegexp(`rest-graphql.test`)"
      - "traefik.http.routers.laravel.entrypoints=web"
      - "traefik.http.services.laravel.loadbalancer.server.port=8080"
      - "traefik.http.services.laravel.loadbalancer.server.scheme=http"

  horizon:
    build:
      target: development
      args:
        USER_ID: ${SPIN_USER_ID}
        GROUP_ID: ${SPIN_GROUP_ID}
    command: php artisan horizon
    volumes:
      - .:/var/www/html/
    networks:
      - base_production
    depends_on:
      - redis
    restart: unless-stopped

  node:
    image: node:22
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app/
    networks:
      - base_production

  redis:
    image: redis:latest
    volumes:
      - redis_data:/data
    networks:
      - base_production
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped

networks:
  base_production:
    external: true

volumes:
  redis_data:
